keycloak:
  realm: monitoring
  internalUrl: http://keycloak.keycloak.svc.cluster.local
  adminSecret: keycloak-admin
  oidcSecret: oidc-client-secrets
  image: adorsys/keycloak-config-cli:6.5.1-26
  hosts: {}
