{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.vault.storeName }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kvMount | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.kubernetesAuthMount | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: external-secrets-vault
            namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: external-secrets
{{- end }}
