vault:
  enabled: false
  storeName: vault-backend
  server: http://vault.vault.svc.cluster.local:8200
  kvMount: monitoring
  kubernetesAuthMount: kubernetes
  role: monitoring-stack
gatewaySecretNamespace: gateway-system
externalSecrets: []
