---
alloy_version: ""
alloy_architecture_map:
  x86_64: amd64
  aarch64: arm64
alloy_package_url: ""
alloy_config_path: /etc/alloy/config.alloy
alloy_config_repository: ""
alloy_config_revision: ""
alloy_config_module_path: ""
alloy_config_pull_frequency: ""
alloy_download_path: /tmp/alloy-linux.zip
alloy_extract_path: /tmp/alloy-linux
alloy_credentials_path: /etc/alloy/credentials
alloy_credentials_environment_file: "{{ alloy_credentials_path }}/environment"
alloy_environment: {}
