---
alloy_namespace: alloy
alloy_service_account_name: alloy
alloy_chart_version: ""
alloy_config_repository: ""
alloy_config_revision: ""
alloy_config_module_path: ""
alloy_config_pull_frequency: ""
alloy_ingest_secret_name: alloy-ingest-client
alloy_host_aliases: []
alloy_environment: {}
