gateway:
  enabled: false
  name: platform-gateway
  namespace: gateway-system
  httpListener: http
  uiListener: ui-https
  ingestListener: ingest-https
  uiHttpRedirect:
    enabled: false
    statusCode: 301
  issuer:
    name: vault-pki
    kind: Issuer
  tls:
    uiSecretName: monitoring-ui-tls
    ingestSecretName: monitoring-ingest-tls
    uiDnsNames: []
    ingestDnsNames: []
  mtlsCaSecret: monitoring-ingest-ca
  uiRoutes: []
  ingestionRoutes: []
