grafana:
  enabled: false
  rootUrl: https://grafana.example.internal
  replicas: 1
  oidcSecret: oidc-client-secrets
  keycloakUrl: https://keycloak.example.internal
  realm: monitoring
  datasources: []
